name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm test

      - name: Grammar
        run: npm run lint:grammar

  build:
    needs: lint-and-test # requires previous step to succeed
    if: always() # Forces this job to run even if 'build' fails
    runs-on: ubuntu-latest
    steps:
      - name: Build prod
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: 'build artifact'
          path: build/prod/*.zip
          if-no-files-found: error
          retention-days: 5
          overwrite: true
